from tabs.fcc import FccTab
from tabs.efc import EFCTab
from tabs.load import LoadTab
from tabs.mst import MistakesTab
from tabs.stats import StatsTab
from tabs.cfg import CfgTab
from tabs.trk import TrackerTab
from tabs.logs import LogsTab
from tabs.sod import SodTab
